# If you only want circle to run on direct commits to main, you can uncomment this out
# and uncomment the filters: *filter-only-main down below too
#
aliases:
 - &filter-only-main
   branches:
     only:
       - main

version: 2
jobs:
  deploy-website:
    docker:
      - image: cimg/node:16.14.0

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "docusaurus-bot@users.noreply.github.com"
            git config --global user.name "Website Deployment Script"
            echo "machine github.com login docusaurus-bot password $GITHUB_TOKEN" > ~/.netrc
            echo "Deploying website..."
            cd website && yarn install && GIT_USER=docusaurus-bot USE_SSH=false yarn deploy
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters: *filter-only-main
