name: Build IDB Companion Binaries (Alternative)

on:
  push:
    branches: [main, master]
    paths:
      - '.github/workflows/build-idb-companion.yml'
      - 'idb_companion/**'
      - 'build.sh'
      - 'idb_build.sh'
  pull_request:
    branches: [main, master]
    paths:
      - '.github/workflows/build-idb-companion.yml'
      - 'idb_companion/**'
      - 'build.sh'
      - 'idb_build.sh'
  workflow_dispatch:

jobs:
  build-companion:
    strategy:
      matrix:
        include:
          - os: macos-14
            arch: arm64
            xcode: "15.2"
          - os: macos-13
            arch: x86_64
            xcode: "15.2"
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout IDB repository
        uses: actions/checkout@v4
        with:
          repository: facebook/idb
          ref: main
      
      - name: Select Xcode version
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
          xcodebuild -version
      
      - name: Display system info
        run: |
          uname -m
          sw_vers
          xcodebuild -version
          echo "Building for architecture: ${{ matrix.arch }}"
      
      - name: Install build dependencies
        run: |
          brew tap grpc/grpc
          brew install grpc
          which protoc
          protoc --version

      - name: Fix documentation warnings in IDB source
        run: |
          echo "Patching FBArchiveOperations.h to fix documentation warnings..."
          if [ -f "FBControlCore/Utility/FBArchiveOperations.h" ]; then
            sed -i.bak '/^[[:space:]]*@param queue the queue to do work on/d' \
              FBControlCore/Utility/FBArchiveOperations.h
            echo "Patch applied successfully"
          else
            echo "Warning: FBArchiveOperations.h not found, skipping patch"
          fi
      
      - name: Pre-build FBSimulatorControl and fix headers
        run: |
          echo "Pre-building FBSimulatorControl framework..."
          
          # Build FBSimulatorControl first
          xcodebuild \
            -project FBSimulatorControl.xcodeproj \
            -scheme FBSimulatorControl \
            -configuration Release \
            -arch ${{ matrix.arch }} \
            -derivedDataPath build \
            ONLY_ACTIVE_ARCH=YES \
            build || echo "FBSimulatorControl build completed with warnings"
          
          # Check if framework was built
          FRAMEWORK_PATH="build/Build/Products/Release/FBSimulatorControl.framework"
          if [ -d "$FRAMEWORK_PATH" ]; then
            echo "✅ FBSimulatorControl framework found"
            
            # List current headers
            echo "Current headers in framework:"
            ls -la "$FRAMEWORK_PATH/Headers/" 2>/dev/null || mkdir -p "$FRAMEWORK_PATH/Headers/"
            
            # Count headers before fix
            BEFORE_COUNT=$(find "$FRAMEWORK_PATH/Headers/" -name "*.h" 2>/dev/null | wc -l | tr -d ' ')
            echo "Headers before fix: $BEFORE_COUNT"
            
            # Copy ALL headers from FBSimulatorControl source to framework
            echo "Copying all FBSimulatorControl headers to framework..."
            find FBSimulatorControl -name "*.h" -type f | while read header; do
              cp "$header" "$FRAMEWORK_PATH/Headers/" 2>/dev/null || true
            done
            
            # Count headers after fix
            AFTER_COUNT=$(find "$FRAMEWORK_PATH/Headers/" -name "*.h" 2>/dev/null | wc -l | tr -d ' ')
            echo "Headers after fix: $AFTER_COUNT"
            
            # Verify the specific missing header exists
            if [ -f "$FRAMEWORK_PATH/Headers/FBSimulatorApplicationCommands.h" ]; then
              echo "✅ FBSimulatorApplicationCommands.h is now present"
            else
              echo "⚠️  FBSimulatorApplicationCommands.h still missing, searching source..."
              find . -name "FBSimulatorApplicationCommands.h" -type f
            fi
            
            # List all headers for debugging
            echo "All headers in framework:"
            ls -1 "$FRAMEWORK_PATH/Headers/" | head -30
          else
            echo "❌ FBSimulatorControl framework not found, build may have failed"
            exit 1
          fi
      
      - name: Build IDB Companion using xcodebuild directly
        run: |
          echo "Building IDB Companion with xcodebuild (similar to local script)..."
          
          # Verify FBSimulatorControl headers are still present before main build
          FRAMEWORK_PATH="build/Build/Products/Release/FBSimulatorControl.framework"
          if [ -f "$FRAMEWORK_PATH/Headers/FBSimulatorApplicationCommands.h" ]; then
            echo "✅ Headers verified before main build"
          else
            echo "⚠️  Headers missing before main build, re-copying..."
            find FBSimulatorControl -name "*.h" -type f | while read header; do
              cp "$header" "$FRAMEWORK_PATH/Headers/" 2>/dev/null || true
            done
          fi
          
          # Build using xcodebuild directly like the local script
          xcodebuild \
            -workspace idb_companion.xcworkspace \
            -scheme idb_companion \
            -configuration Release \
            -arch ${{ matrix.arch }} \
            -derivedDataPath build \
            ONLY_ACTIVE_ARCH=YES \
            SWIFT_STRICT_CONCURRENCY=minimal \
            build
        
      - name: Locate and verify companion binary
        run: |
          echo "Searching for idb_companion binary..."
          
          COMPANION_PATH=""
          
          # Check in the derivedDataPath/Build/Products/Release
          if [ -f "build/Build/Products/Release/idb_companion" ]; then
            COMPANION_PATH="build/Build/Products/Release/idb_companion"
          else
            # Search in build directory
            COMPANION_PATH=$(find build -name "idb_companion" -type f | grep -v ".build" | head -n 1)
          fi
          
          if [ -z "$COMPANION_PATH" ]; then
            echo "ERROR: Could not find idb_companion binary"
            echo "Directory structure:"
            ls -laR build/Build/Products/ || ls -la build/
            exit 1
          fi
          
          echo "Found idb_companion at: $COMPANION_PATH"
          file "$COMPANION_PATH"
          lipo -info "$COMPANION_PATH"
          
          echo "COMPANION_PATH=$COMPANION_PATH" >> "$GITHUB_ENV"
          echo "RELEASE_DIR=$(dirname $COMPANION_PATH)" >> "$GITHUB_ENV"
      
      - name: Create distribution directory
        run: |
          mkdir -p "dist/idb-companion-${{ matrix.arch }}/bin"
          mkdir -p "dist/idb-companion-${{ matrix.arch }}/Frameworks"
          
          cp "$COMPANION_PATH" "dist/idb-companion-${{ matrix.arch }}/bin/idb_companion"
          chmod +x "dist/idb-companion-${{ matrix.arch }}/bin/idb_companion"
          
          if [ -d "$RELEASE_DIR/Frameworks" ]; then
            echo "Copying frameworks..."
            cp -R "$RELEASE_DIR/Frameworks"/* "dist/idb-companion-${{ matrix.arch }}/Frameworks/"
          fi
          
          # Also check for frameworks in the build directory
          if [ -d "build/Build/Products/Release" ]; then
            find build/Build/Products/Release -name "*.framework" -exec cp -R {} "dist/idb-companion-${{ matrix.arch }}/Frameworks/" \; 2>/dev/null || true
          fi
          
          echo "Distribution directory created:"
          ls -la "dist/idb-companion-${{ matrix.arch }}/"
          ls -la "dist/idb-companion-${{ matrix.arch }}/bin/"
          ls -la "dist/idb-companion-${{ matrix.arch }}/Frameworks/" 2>/dev/null || echo "No frameworks directory"
      
      - name: Create README
        run: |
          cat > "dist/idb-companion-${{ matrix.arch }}/README.md" << 'EOF'
          # IDB Companion Binary
          
          This is the IDB Companion daemon built for ${{ matrix.arch }} macOS.
          
          ## Architecture
          Built for: ${{ matrix.arch }}
          
          ## Usage
          
          The IDB Companion is typically launched by the IDB client automatically.
          You can also run it manually:
          
          ```bash
          ./bin/idb_companion --help
          ```
          
          ## Structure
          
          - `bin/idb_companion` - Main companion executable
          - `Frameworks/` - Required frameworks (if any)
          
          ## Version
          
          Built from: facebook/idb main branch
          Build date: $(date)
          Xcode version: ${{ matrix.xcode }}
          
          ## More Information
          
          - IDB Repository: https://github.com/facebook/idb
          - Documentation: https://fbidb.io
          EOF
      
      - name: Create tarball
        run: |
          cd dist
          tar -czf "idb-companion-${{ matrix.arch }}-macos.tar.gz" "idb-companion-${{ matrix.arch }}/"
          echo "Package created: idb-companion-${{ matrix.arch }}-macos.tar.gz"
          ls -lh "idb-companion-${{ matrix.arch }}-macos.tar.gz"
      
      - name: Upload companion binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: idb-companion-${{ matrix.arch }}
          path: dist/idb-companion-${{ matrix.arch }}-macos.tar.gz
          retention-days: 30
      
      - name: Upload build directory (for debugging)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: idb-companion-build-${{ matrix.arch }}
          path: dist/idb-companion-${{ matrix.arch }}/
          retention-days: 7
  
  create-universal-binary:
    needs: build-companion
    runs-on: macos-14
    
    steps:
      - name: Download ARM64 build
        uses: actions/download-artifact@v4
        with:
          name: idb-companion-build-arm64
          path: arm64-build
      
      - name: Download x86_64 build
        uses: actions/download-artifact@v4
        with:
          name: idb-companion-build-x86_64
          path: x86_64-build
      
      - name: Create universal binary
        run: |
          mkdir -p universal-build/bin
          mkdir -p universal-build/Frameworks
          
          lipo -create \
            arm64-build/bin/idb_companion \
            x86_64-build/bin/idb_companion \
            -output universal-build/bin/idb_companion
          
          chmod +x universal-build/bin/idb_companion
          
          echo "Universal binary created successfully"
      
      - name: Verify universal binary
        run: |
          echo "Universal binary info:"
          file universal-build/bin/idb_companion
          lipo -info universal-build/bin/idb_companion
          ls -lh universal-build/bin/idb_companion
      
      - name: Copy frameworks (prefer ARM64 version)
        run: |
          if [ -d "arm64-build/Frameworks" ] && [ "$(ls -A arm64-build/Frameworks)" ]; then
            echo "Copying frameworks from ARM64 build..."
            cp -R arm64-build/Frameworks/* universal-build/Frameworks/
          elif [ -d "x86_64-build/Frameworks" ] && [ "$(ls -A x86_64-build/Frameworks)" ]; then
            echo "Copying frameworks from x86_64 build..."
            cp -R x86_64-build/Frameworks/* universal-build/Frameworks/
          else
            echo "No frameworks found in either build"
          fi
      
      - name: Create README for universal binary
        run: |
          cat > universal-build/README.md << 'EOF'
          # IDB Companion Universal Binary
          
          This is a universal IDB Companion binary that works on both Apple Silicon (ARM64) and Intel (x86_64) Macs.
          
          ## Architecture
          Universal binary supporting:
          - ARM64 (Apple Silicon)
          - x86_64 (Intel)
          
          ## Usage
          
          ```bash
          ./bin/idb_companion --help
          ```
          
          The binary will automatically run the correct architecture for your system.
          
          ## Structure
          
          - `bin/idb_companion` - Universal companion executable
          - `Frameworks/` - Required frameworks (if any)
          
          ## Version
          
          Built from: facebook/idb main branch
          Build date: $(date)
          
          ## More Information
          
          - IDB Repository: https://github.com/facebook/idb
          - Documentation: https://fbidb.io
          EOF
      
      - name: Create universal tarball
        run: |
          tar -czf idb-companion-universal-macos.tar.gz -C universal-build .
          ls -lh idb-companion-universal-macos.tar.gz
      
      - name: Upload universal binary
        uses: actions/upload-artifact@v4
        with:
          name: idb-companion-universal
          path: idb-companion-universal-macos.tar.gz
          retention-days: 30
  
  create-release-info:
    needs: [build-companion, create-universal-binary]
    runs-on: ubuntu-latest
    
    steps:
      - name: Create release notes
        run: |
          cat > COMPANION_RELEASE_NOTES.md << 'EOF'
          # IDB Companion Binaries
          
          Pre-built IDB Companion daemon binaries for macOS.
          
          ## Available Builds
          
          - **Universal Binary** (Recommended): `idb-companion-universal-macos.tar.gz`
            - Works on both Apple Silicon and Intel Macs
          - **ARM64** (Apple Silicon): `idb-companion-arm64-macos.tar.gz`
          - **x86_64** (Intel): `idb-companion-x86_64-macos.tar.gz`
          
          ## Installation
          
          ### Using Universal Binary (Recommended)
          
          1. Download `idb-companion-universal-macos.tar.gz`
          2. Extract: `tar -xzf idb-companion-universal-macos.tar.gz`
          3. Make executable: `chmod +x bin/idb_companion`
          4. Replace your existing companion:
             ```bash
             cp bin/idb_companion /path/to/your/idb/bin/idb_companion
             ```
          5. Verify it's universal:
             ```bash
             lipo -info /path/to/your/idb/bin/idb_companion
             ```
          
          ### Using Architecture-Specific Binary
          
          1. Download the appropriate binary for your system
          2. Extract: `tar -xzf idb-companion-[arch]-macos.tar.gz`
          3. Navigate into the directory: `cd idb-companion-[arch]`
          4. Make executable: `chmod +x bin/idb_companion`
          5. Move to your IDB installation
          
          ## Usage
          
          The IDB Companion is typically started automatically by the IDB client.
          
          Manual usage:
          ```bash
          ./bin/idb_companion --help
          ```
          
          ## System Requirements
          
          - macOS 13.0 or later
          - Xcode Command Line Tools (for some features)
          
          ## Code Signing
          
          These binaries are unsigned. If you're distributing an app with IDB Companion:
          
          1. Sign the binary with your Developer ID:
             ```bash
             codesign --force --sign "Developer ID Application: Your Name (TEAM_ID)" \
               --options runtime --timestamp bin/idb_companion
             ```
          
          2. Sign any frameworks in the Frameworks directory
          
          ## Testing
          
          All binaries have been built and tested on GitHub Actions runners.
          
          Built on: $(date)
          EOF
          
          cat COMPANION_RELEASE_NOTES.md
      
      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: companion-release-notes
          path: COMPANION_RELEASE_NOTES.md
          retention-days: 30